include:
  - ./docker-compose-base.yml

services:
  ragflow-web:
    depends_on:
      mysql:
        condition: service_healthy
    image: ragflow-web:dev
    container_name: ragflow-web
    ports:
      - 80:80
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - RAGFLOW_SERVER_API_HOST=ragflow-server
    networks:
      - ragflow
    restart: on-failure

  ragflow-server:
    depends_on:
      mysql:
        condition: service_healthy
    image: ragflow-server:dev
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
    networks:
      - ragflow
    restart: on-failure

  ragflow-task-execution-0:
    depends_on:
      mysql:
        condition: service_healthy
    image: ragflow-task-execution:dev
    container_name: ragflow-task-execution-0
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - WS=0
    networks:
      - ragflow
    restart: on-failure

  ragflow-task-execution-1:
    depends_on:
      mysql:
        condition: service_healthy
    image: ragflow-task-execution:dev
    container_name: ragflow-task-execution-1
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - WS=1
    networks:
      - ragflow
    restart: on-failure